// flow-typed signature: f1487f087e415cab8b0b7aea27e254d8
// flow-typed version: <<STUB>>/page_v1.8.6/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'page'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'page' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'page/page' {
  declare module.exports: any
}

// Filename aliases
declare module 'page/index' {
  declare module.exports: $Exports<'page'>
}
declare module 'page/index.js' {
  declare module.exports: $Exports<'page'>
}
declare module 'page/page.js' {
  declare module.exports: $Exports<'page/page'>
}
